import type { Metadata } from "next";
import "./globals.css";
import { dbConnect } from "@/lib/mongo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const connection = await dbConnect();
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
